### ISSUE TITLE
APK or how to compile

### ISSUE THREAD

**Issue by BennPaul** [dupontgu/simple-cast#1]
Sorry, I'm new to Android apps. Is there an APK in your repository or how do I build it?

**Comment by dupontgu** [comment]
Hi @BennPaul, I do not have an APK anywhere, but I can throw one up in the `Releases` for this project soon.  In the meantime, it's pretty simple to build.  Just download Android Studio and then open (or import?) the `build.gradle` file in the root of this repo.  Once everything loads, you should be able to select `Build -> Make Project`.  This will automatically create a `build` directory and drop the APK in when it's finished.

**Comment by BennPaul** [comment]
Hi @dupontgu ,
thanks for your answer. I'll give it a try on the weekend.

**Comment by phakeEHS** [comment]
Hi @dupontgu, could you put an APK in the Releases? I keep getting an error when building your project. :(

**Comment by phakeEHS** [comment]
@dupontgu Oops, I think I got it. Needed the Android 9.0 Android SDK's.

https://github.com/flutter/flutter/issues/26832

Slick app - I am a huge fan of the Vinyl Cast app by Allen Schober but wanted something I could cast to like your Pi setup.

**Comment by ineiva** [comment]
Hi @dupontgu, I just wanted to thank you so much for your tutorial, and to ask you to please upload the install-ready APK to resources if you have the chance. I tried downloading Android Studio and following your instructions here in this issue, but I kept getting cryptic errors and no APK (it doesn't help that I am at a complete loss when looking at Android Studio, it's completely beyond the scope of my abilities). 

In the meantime I managed to stream the audio using the VLC Android app, since it opens webcasts and is able to cast to Chromecast audio groups, but I would love to be able to use your solution 100%! Thank you again, you have made my day!!
